from steem import Steem
s = Steem()

print(s.get_blog('awarenessraiser', -1, 1))

'''
schemelab@metta:~/prg/vivacoin/steem-voting/src/etc$ python3 get_blog.py
[{'comment': {'id': 10147808, 'author': 'awarenessraiser', 'permlink': 'vlog-13-introduced-high-level-music-ceo-to-steemit-luxury-clips-inside', 'category': 'music', 'parent_author': '', 'parent_permlink': 'music', 'title': 'VLOG #13: Introduced High Level Music CEO To STEEMIT + Luxury Clips Inside!!', 'body': '<html>\n<p>Yesterday was all the way dope! I brushed shoulders with some heavy hitters in the music game who works with <em>BET</em>, <em>Radio Shows</em> and <em>Top Notch music artists</em> in the game such as <em>Ariana Grande</em>. It is funny because this event came to me very unexpectedly and I had no idea who I was even about to meet. I also met another guy who works with <em>Eric Thomas</em>, the motivational speaker very up close and personal.&nbsp;Be sure to watch till the end so you can see all the footage!</p>\n<p>Be sure to check out the <strong>Luxury pics and short snippet vids I include</strong> in this vid of the Media Productions Studio.</p>\n<blockquote>Life is always full of surprises. You never know who you are going to meet.</blockquote>\n<p>https://youtu.be/pZFcPglntNg</p>\n<p>One of the pics from inside the vid:</p>\n<p>https://s2.postimg.org/41s5x5mjd/IMG_0072.jpg</p>\n<p>Music By:</p>\n<p>https://youtu.be/e6nXweiNaeI</p>\n<p><strong>Let me know what you think in the comments below &amp; Show your girl some</strong> <strong>Love</strong>! ♥</p>\n<p><br></p>\n<p><br></p>\n<p>Love,</p>\n<p><em>Hannah (Remember Who You Are)</em></p>\n<p><br></p>\n<p><br></p>\n</html>', 'json_metadata': '{"tags":["music","money","success","steemit","video"],"image":["https://img.youtube.com/vi/pZFcPglntNg/0.jpg","https://s2.postimg.org/41s5x5mjd/IMG_0072.jpg","https://img.youtube.com/vi/e6nXweiNaeI/0.jpg"],"links":["https://youtu.be/pZFcPglntNg","https://youtu.be/e6nXweiNaeI"],"app":"steemit/0.1","format":"html"}', 'last_update': '2017-08-15T08:28:27', 'created': '2017-08-14T23:45:00', 'active': '2017-08-15T09:51:39', 'last_payout': '1970-01-01T00:00:00', 'depth': 0, 'children': 9, 'net_rshares': '21767291070765', 'abs_rshares': '21767291070765', 'vote_rshares': '21767291070765', 'children_abs_rshares': '21815143314638', 'cashout_time': '2017-08-21T23:45:00', 'max_cashout_time': '1969-12-31T23:59:59', 'total_vote_weight': 4692015, 'reward_weight': 10000, 'total_payout_value': '0.000 SBD', 'curator_payout_value': '0.000 SBD', 'author_rewards': 0, 'net_votes': 53, 'root_comment': 10147808, 'max_accepted_payout': '1000000.000 SBD', 'percent_steem_dollars': 10000, 'allow_replies': True, 'allow_votes': True, 'allow_curation_rewards': True, 'beneficiaries': []}, 'blog': 'awarenessraiser', 'reblog_on': '1970-01-01T00:00:00', 'entry_id': 41}]
schemelab@metta:~/prg/vivacoin/steem-voting/src/etc$
'''
